"""empty message

Revision ID: 764a37a7062b
Revises: a767200e907f
Create Date: 2024-09-13 01:44:56.315861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764a37a7062b'
down_revision = 'a767200e907f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
